
/*
 * 
 */

package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Oct 21 02:14:54 CEST 2014
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "HelloWorldService", 
                  wsdlLocation = "http://localhost:8080/TestWebService/HelloWorld?wsdl",
                  targetNamespace = "http://webservices/") 
public class HelloWorldService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservices/", "HelloWorldService");
    public final static QName HelloWorldPort = new QName("http://webservices/", "HelloWorldPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/TestWebService/HelloWorld?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/TestWebService/HelloWorld?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public HelloWorldService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWorldService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    /*public HelloWorldService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public HelloWorldService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloWorldService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }*/

    /**
     * 
     * @return
     *     returns HelloWorldRemote
     */
    @WebEndpoint(name = "HelloWorldPort")
    public HelloWorldRemote getHelloWorldPort() {
        return super.getPort(HelloWorldPort, HelloWorldRemote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldRemote
     */
    @WebEndpoint(name = "HelloWorldPort")
    public HelloWorldRemote getHelloWorldPort(WebServiceFeature... features) {
        return super.getPort(HelloWorldPort, HelloWorldRemote.class, features);
    }

}
